"""DB-backed tests for the entities schema, seeder, and service API (C1).

These run against a live Postgres resolved from (in order) ``ENTITIES_TEST_DSN``,
``DATABASE_DIRECT_URL``, or ``DATABASE_URL`` — so they execute automatically in CI
(which sets ``DATABASE_DIRECT_URL`` to a throwaway ``civicsignals_test`` DB) and
for any dev with the stack up, while skipping cleanly when no DB is configured.
This is the same opt-in-via-env convention as ``tests/test_seed_demo.py``, but
wired to the CI DSN so the schema/seed actually get exercised in CI.

The DSN must be an ``asyncpg`` URL, e.g.::

    ENTITIES_TEST_DSN=postgresql+asyncpg://civic:civic@localhost:55432/civicsignals

Each test runs against a throwaway schema created fresh from the SQLAlchemy
metadata (plus the ``pg_trgm`` extension the trigram index needs), so they do not
depend on migration ordering and never touch another module's tables. A separate
test applies the *actual Alembic migration* to confirm the generated DDL works.
"""

from __future__ import annotations

import os
import uuid
from collections.abc import AsyncIterator
from types import ModuleType

import pytest
import pytest_asyncio
from sqlalchemy import Connection, Table, func, select, text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

from civicsignals_api.db import Base
from civicsignals_api.modules.entities import seeding, services
from civicsignals_api.modules.entities.models import Entity, EntityKind, Geo

_DSN = (
    os.environ.get("ENTITIES_TEST_DSN")
    or os.environ.get("DATABASE_DIRECT_URL")
    or os.environ.get("DATABASE_URL")
)
pytestmark = pytest.mark.skipif(_DSN is None, reason="no Postgres DSN configured")

# Only the entities tables — never drop another module's tables.
_TABLES: list[Table] = [
    Base.metadata.tables[name] for name in ("entities_entity", "entities_kind", "entities_geo")
]


@pytest_asyncio.fixture
async def session() -> AsyncIterator[AsyncSession]:
    assert _DSN is not None
    engine = create_async_engine(_DSN)
    async with engine.begin() as conn:
        await conn.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
        await conn.run_sync(Base.metadata.drop_all, tables=_TABLES)
        await conn.run_sync(Base.metadata.create_all, tables=_TABLES)
    try:
        async with AsyncSession(engine) as sess:
            yield sess
    finally:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all, tables=_TABLES)
        await engine.dispose()


async def _counts(session: AsyncSession) -> dict[str, int]:
    out: dict[str, int] = {}
    for name, model in (("entity", Entity), ("kind", EntityKind), ("geo", Geo)):
        result = await session.execute(select(func.count()).select_from(model))
        out[name] = int(result.scalar_one())
    # Close the implicit read transaction so callers can ``session.begin()`` again.
    await session.rollback()
    return out


def _load_migration_module() -> ModuleType:
    """Import the C1 migration by file path (alembic/versions isn't a package)."""
    import importlib.util
    from pathlib import Path

    # tests/ -> entities/ -> modules/ -> civicsignals_api/ -> src/ -> apps/api/
    api_root = Path(__file__).resolve().parents[5]
    path = api_root / "alembic" / "versions" / "f8de6b788783_entities_kind_geo_entity_tables.py"
    spec = importlib.util.spec_from_file_location("c1_entities_migration", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_migration_upgrade(conn: Connection) -> set[str]:
    """Run the entities migration's ``upgrade()`` on a *sync* connection.

    Driven via ``AsyncConnection.run_sync`` so it works with the asyncpg engine
    (no separate sync driver needed). Returns the ``entities_*`` table names that
    exist afterwards.
    """
    from alembic.operations import Operations
    from alembic.runtime.migration import MigrationContext

    migration = _load_migration_module()
    for tbl in ("entities_entity", "entities_kind", "entities_geo"):
        conn.exec_driver_sql(f"DROP TABLE IF EXISTS {tbl} CASCADE")
    with Operations.context(MigrationContext.configure(conn)):
        migration.upgrade()
    rows = conn.exec_driver_sql(
        "SELECT tablename FROM pg_tables WHERE tablename LIKE 'entities_%'"
    ).fetchall()
    return {r[0] for r in rows}


@pytest.mark.asyncio
async def test_entities_migration_applies(session: AsyncSession) -> None:
    """The generated Alembic DDL creates exactly the three entity tables on PG.

    Drops the metadata-created tables, then runs the migration's own
    ``upgrade()`` ops body against a clean slate, proving the autogenerated DDL
    is valid Postgres and touches only ``entities_*`` objects.
    """
    assert _DSN is not None
    engine = create_async_engine(_DSN)
    try:
        async with engine.begin() as conn:
            tables = await conn.run_sync(_run_migration_upgrade)
        assert tables == {"entities_entity", "entities_kind", "entities_geo"}
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_seed_populates_all_sources(session: AsyncSession) -> None:
    async with session.begin():
        stats = await seeding.seed_entities(session)
    assert stats.kinds == len(seeding.KIND_SEED)
    assert stats.by_source["nces"] == 6
    assert stats.by_source["ipeds"] == 6
    # 6 local govs in the census fixture (2 state rows are skipped — synthesized).
    assert stats.by_source["census_gov"] == 6
    counts = await _counts(session)
    assert counts["kind"] == len(seeding.KIND_SEED)
    # 6 NCES + 6 IPEDS + 6 census local-gov + 4 synthesized state roots.
    assert counts["entity"] == 6 + 6 + 6 + 4


@pytest.mark.asyncio
async def test_seed_is_idempotent(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    first = await _counts(session)
    async with session.begin():
        await seeding.seed_entities(session)
    second = await _counts(session)
    assert first == second


@pytest.mark.asyncio
async def test_hierarchy_links_children_to_state(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    # Washington state root.
    wa = (
        await session.execute(select(Entity).where(Entity.type == "state", Entity.state == "WA"))
    ).scalar_one()
    children = await services.list_children(session, wa.id, limit=100)
    # Every WA non-state entity is parented to the WA state row.
    assert children.items
    assert all(c.parent_id == wa.id for c in children.items)
    assert all(c.state == "WA" for c in children.items)
    # Northshore SD (from the NCES fixture) is one of them.
    names = {c.name for c in children.items}
    assert "Northshore School District" in names


@pytest.mark.asyncio
async def test_get_entity_and_resolve_by_identifier(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    nsd = await services.resolve_entity_by_identifier(session, "nces_leaid", "5304350")
    assert nsd is not None
    assert nsd.name == "Northshore School District"
    assert nsd.type == "school_district"
    assert nsd.enrollment == 23400
    # round-trip through get_entity
    again = await services.get_entity(session, nsd.id)
    assert again is not None and again.id == nsd.id
    # unknown id -> None
    assert await services.get_entity(session, uuid.uuid4()) is None
    # IPEDS sector mapping: SECTOR=4 -> community_college.
    bellevue = await services.resolve_entity_by_identifier(session, "ipeds_unitid", "237118")
    assert bellevue is not None and bellevue.type == "community_college"
    uw = await services.resolve_entity_by_identifier(session, "ipeds_unitid", "236948")
    assert uw is not None and uw.type == "university"


@pytest.mark.asyncio
async def test_search_filters_by_kind_and_state(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    # Filter by kind slug + state.
    page = await services.search_entities(
        session,
        services.EntityFilters(kind_slugs=["school_district"], states=["TX"]),
        limit=100,
    )
    assert page.items
    assert all(e.type == "school_district" and e.state == "TX" for e in page.items)

    # Filter by type set.
    higher_ed = await services.search_entities(
        session,
        services.EntityFilters(types=["university", "community_college"]),
        limit=100,
    )
    assert {e.type for e in higher_ed.items} <= {"university", "community_college"}

    # Name search (trigram-backed ILIKE).
    by_name = await services.search_entities(
        session, services.EntityFilters(q="Houston"), limit=100
    )
    names = {e.name for e in by_name.items}
    assert any("Houston" in n for n in names)


@pytest.mark.asyncio
async def test_search_filter_by_geo(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    seattle = await services.resolve_entity_by_identifier(
        session, "census_gid", "53-00033-3000-5363000"
    )
    assert seattle is not None and seattle.geo_id is not None
    page = await services.search_entities(
        session, services.EntityFilters(geo_id=seattle.geo_id), limit=100
    )
    assert page.items
    assert all(e.geo_id == seattle.geo_id for e in page.items)


@pytest.mark.asyncio
async def test_search_cursor_pagination(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    total = (await _counts(session))["entity"]

    seen: list[uuid.UUID] = []
    cursor: str | None = None
    pages = 0
    while True:
        page = await services.search_entities(session, cursor=cursor, limit=5)
        seen.extend(e.id for e in page.items)
        pages += 1
        if page.next_cursor is None:
            break
        cursor = page.next_cursor
        assert pages < 50, "pagination did not terminate"

    # Walked every row exactly once, in id order, across multiple pages.
    assert len(seen) == total
    assert len(set(seen)) == total
    assert seen == sorted(seen)
    assert pages > 1


@pytest.mark.asyncio
async def test_geo_hierarchy_and_kind_taxonomy(session: AsyncSession) -> None:
    async with session.begin():
        await seeding.seed_entities(session)
    # Kind taxonomy fully seeded and queryable.
    kinds = (await session.execute(select(EntityKind))).scalars().all()
    assert {k.slug for k in kinds} == {row[0] for row in seeding.KIND_SEED}
    # Geo rows exist for the states + places we loaded.
    wa_state_geo = (
        await session.execute(select(Geo).where(Geo.geo_id == "53"))
    ).scalar_one_or_none()
    assert wa_state_geo is not None and wa_state_geo.level == "state"
    seattle_geo = (
        await session.execute(select(Geo).where(Geo.geo_id == "5363000"))
    ).scalar_one_or_none()
    assert seattle_geo is not None and seattle_geo.level == "place"


@pytest.mark.asyncio
async def test_public_routes_list_get_children(session: AsyncSession) -> None:
    """The public read endpoints serve the directory without X-Workspace-Id (C1 req 5).

    Driven through an in-process ASGI transport (``httpx.AsyncClient``) so the
    request runs in the test's event loop. The endpoint dependency is overridden
    with a fresh session per request (bound to the same engine) so the route's
    own session lifecycle is exercised, independent of the seeding session.
    """
    import httpx

    from civicsignals_api.db import get_session
    from civicsignals_api.main import app

    async with session.begin():
        await seeding.seed_entities(session)
    wa_state_id = (
        await session.execute(select(Entity.id).where(Entity.type == "state", Entity.state == "WA"))
    ).scalar_one()
    await session.rollback()

    assert _DSN is not None
    engine = create_async_engine(_DSN)

    async def _override() -> AsyncIterator[AsyncSession]:
        async with AsyncSession(engine) as req_session:
            yield req_session

    app.dependency_overrides[get_session] = _override
    transport = httpx.ASGITransport(app=app)
    try:
        async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
            # List with a kind+state filter; no workspace header supplied on purpose.
            resp = await client.get(
                "/api/v1/entities", params={"kind": "school_district", "state": "TX"}
            )
            assert resp.status_code == 200
            body = resp.json()
            assert body["items"]
            assert all(e["type"] == "school_district" and e["state"] == "TX" for e in body["items"])

            # Fetch one, then its children via the hierarchy endpoint.
            get_resp = await client.get(f"/api/v1/entities/{wa_state_id}")
            assert get_resp.status_code == 200
            assert get_resp.json()["name"] == "State of Washington"

            kids = await client.get(f"/api/v1/entities/{wa_state_id}/children")
            assert kids.status_code == 200
            assert kids.json()["items"]

            # Unknown id -> RFC 7807 problem+json 404.
            missing = await client.get(f"/api/v1/entities/{uuid.uuid4()}")
            assert missing.status_code == 404
            assert "application/problem+json" in missing.headers["content-type"]
    finally:
        app.dependency_overrides.pop(get_session, None)
        await engine.dispose()
