"""B8 auth api token (workspace + personal access tokens)

Revision ID: 129c1e8af6d9
Revises: b532c18ae083
Create Date: 2026-05-22 09:16:01.194479
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "129c1e8af6d9"
down_revision: str | None = "b532c18ae083"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_api_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum(
                "workspace", "personal", name="auth_api_token_type", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("token_prefix", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("scopes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["accounts_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["accounts_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["accounts_workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_api_token_token_hash"), "auth_api_token", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_auth_api_token_token_type"), "auth_api_token", ["token_type"], unique=False
    )
    op.create_index(op.f("ix_auth_api_token_user_id"), "auth_api_token", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_auth_api_token_workspace_id"), "auth_api_token", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_api_token_workspace_id"), table_name="auth_api_token")
    op.drop_index(op.f("ix_auth_api_token_user_id"), table_name="auth_api_token")
    op.drop_index(op.f("ix_auth_api_token_token_type"), table_name="auth_api_token")
    op.drop_index(op.f("ix_auth_api_token_token_hash"), table_name="auth_api_token")
    op.drop_table("auth_api_token")
    # ### end Alembic commands ###
