"""B5 workspaces: organization, workspace, membership, last_active

Revision ID: 68fd32317974
Revises: f8de6b788783
Create Date: 2026-05-22 06:58:40.623856
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "68fd32317974"
down_revision: str | None = "f8de6b788783"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts_organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("billing_email", postgresql.CITEXT(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts_workspace",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("country_default", sa.String(length=2), server_default="US", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["accounts_organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["accounts_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accounts_workspace_organization_id"),
        "accounts_workspace",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounts_workspace_owner_id"), "accounts_workspace", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_accounts_workspace_slug"), "accounts_workspace", ["slug"], unique=True)
    op.create_table(
        "accounts_member",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "MEMBER",
                "VIEWER",
                name="accounts_membership_role",
                native_enum=False,
                length=16,
            ),
            server_default="member",
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["accounts_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["accounts_user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["accounts_workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_accounts_member_ws_user"),
    )
    op.create_index(
        op.f("ix_accounts_member_user_id"), "accounts_member", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_member_workspace_id"), "accounts_member", ["workspace_id"], unique=False
    )
    op.add_column("accounts_user", sa.Column("last_active_workspace_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_accounts_user_last_active_workspace",
        "accounts_user",
        "accounts_workspace",
        ["last_active_workspace_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_accounts_user_last_active_workspace", "accounts_user", type_="foreignkey"
    )
    op.drop_column("accounts_user", "last_active_workspace_id")
    op.drop_index(op.f("ix_accounts_member_workspace_id"), table_name="accounts_member")
    op.drop_index(op.f("ix_accounts_member_user_id"), table_name="accounts_member")
    op.drop_table("accounts_member")
    op.drop_index(op.f("ix_accounts_workspace_slug"), table_name="accounts_workspace")
    op.drop_index(op.f("ix_accounts_workspace_owner_id"), table_name="accounts_workspace")
    op.drop_index(op.f("ix_accounts_workspace_organization_id"), table_name="accounts_workspace")
    op.drop_table("accounts_workspace")
    op.drop_table("accounts_organization")
    # ### end Alembic commands ###
