"""extraction relevance decisions

Creates ``extraction_relevance_decision``, owned by the extraction module: the
Stage-2 relevance-gate decision log used for retrospective FP/FN analysis
(doc 19 §3.4, TODO E8). Touches only this module's table.

Revision ID: 72f1737aad7b
Revises:
Create Date: 2026-05-22 05:10:54.327022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "72f1737aad7b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_relevance_decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_document_id", sa.String(length=64), nullable=False),
        sa.Column("recipe_id", sa.String(length=128), nullable=False),
        sa.Column("relevant", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_extraction_relevance_decision_raw_document",
        "extraction_relevance_decision",
        ["raw_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_extraction_relevance_decision_recipe_created",
        "extraction_relevance_decision",
        ["recipe_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_extraction_relevance_decision_recipe_created",
        table_name="extraction_relevance_decision",
    )
    op.drop_index(
        "ix_extraction_relevance_decision_raw_document", table_name="extraction_relevance_decision"
    )
    op.drop_table("extraction_relevance_decision")
    # ### end Alembic commands ###
