"""extraction job and candidate tables (E1)

Owned by the ``extraction`` module (doc 06 §3, §4) — touches only ``extraction_*``.
Creates the two tables that make the orchestration pipeline observable and lossless
(doc 19 §1): ``extraction_job`` tracks one run of the funnel per raw document
(status/stage/error, the dead-letter on failure), and ``extraction_candidate``
stages the candidate signal records the extract stage emits so E4/E5 can validate,
score, dedupe, and promote them once ``signals_signal`` exists. Both PKs are
generated application-side (``models._new_uuid``), so this migration needs no
server-side UUID function / pgcrypto extension.

Chains after the current single head (the B5/D3 merge), keeping one linear head.

Revision ID: 9838860e8504
Revises: 02e0276be741
Create Date: 2026-05-22 08:56:20.650932
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9838860e8504"
down_revision: str | None = "02e0276be741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_candidate",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.String(length=255), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=True),
        sa.Column(
            "fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("dedup_key", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), server_default=sa.text("'new'"), nullable=False),
        sa.Column(
            "extraction_method",
            sa.String(length=32),
            server_default=sa.text("'llm'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_extraction_candidate_dedup_key", "extraction_candidate", ["dedup_key"], unique=False
    )
    op.create_index("ix_extraction_candidate_job", "extraction_candidate", ["job_id"], unique=False)
    op.create_index(
        "ix_extraction_candidate_raw_document",
        "extraction_candidate",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "extraction_job",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_document_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_document_id", name="extraction_job_raw_document_uq"),
    )
    op.create_index(
        "ix_extraction_job_status_created", "extraction_job", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_extraction_job_status_created", table_name="extraction_job")
    op.drop_table("extraction_job")
    op.drop_index("ix_extraction_candidate_raw_document", table_name="extraction_candidate")
    op.drop_index("ix_extraction_candidate_job", table_name="extraction_candidate")
    op.drop_index("ix_extraction_candidate_dedup_key", table_name="extraction_candidate")
    op.drop_table("extraction_candidate")
    # ### end Alembic commands ###
