"""J1 pipeline stage and item tables

Revision ID: 9bca2a281041
Revises: 467a515ea5a6
Create Date: 2026-05-22 08:25:27.565795
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9bca2a281041"
down_revision: str | None = "467a515ea5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_stage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name="ck_pipeline_stage_position_gte0"),
        sa.ForeignKeyConstraint(["workspace_id"], ["accounts_workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_pipeline_stage_ws_name"),
    )
    op.create_index(
        op.f("ix_pipeline_stage_workspace_id"), "pipeline_stage", ["workspace_id"], unique=False
    )
    op.create_table(
        "pipeline_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("value_estimate", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "won",
                "lost",
                "disqualified",
                "archived",
                name="pipeline_item_status",
                native_enum=False,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_estimate IS NULL OR value_estimate >= 0", name="ck_pipeline_item_value_gte0"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["accounts_member.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["stage_id"], ["pipeline_stage.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["accounts_workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_item_owner_id"), "pipeline_item", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_item_signal_id"), "pipeline_item", ["signal_id"], unique=False
    )
    op.create_index(op.f("ix_pipeline_item_stage_id"), "pipeline_item", ["stage_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_item_workspace_id"), "pipeline_item", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_item_workspace_id"), table_name="pipeline_item")
    op.drop_index(op.f("ix_pipeline_item_stage_id"), table_name="pipeline_item")
    op.drop_index(op.f("ix_pipeline_item_signal_id"), table_name="pipeline_item")
    op.drop_index(op.f("ix_pipeline_item_owner_id"), table_name="pipeline_item")
    op.drop_table("pipeline_item")
    op.drop_index(op.f("ix_pipeline_stage_workspace_id"), table_name="pipeline_stage")
    op.drop_table("pipeline_stage")
    # ### end Alembic commands ###
