"""B3 auth: auth_password_reset_token

Adds the single-use, hashed password-reset token table for the B3 password
reset flow. Mirrors the pattern of ``auth_email_verification_token`` (B1):
only the SHA-256 hex digest of the opaque token is stored (threat-model §4.2).

``consumed_at`` enforces single-use. On a successful reset the service layer
also marks all *other* pending reset tokens for the same user consumed so old
reset links cannot be replayed.

Revision ID: b3c1d2e4f5a6
Revises: aa34b8a78218
Create Date: 2026-05-22 12:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b3c1d2e4f5a6"
down_revision: str | None = "aa34b8a78218"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_password_reset_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_password_reset_token_token_hash"),
        "auth_password_reset_token",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_password_reset_token_user_id"),
        "auth_password_reset_token",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_password_reset_token_user_id"),
        table_name="auth_password_reset_token",
    )
    op.drop_index(
        op.f("ix_auth_password_reset_token_token_hash"),
        table_name="auth_password_reset_token",
    )
    op.drop_table("auth_password_reset_token")
    # ### end Alembic commands ###
