"""J1 pipeline_item owner_id loose ref drop FK

Revision ID: d7dd938017a7
Revises: 9bca2a281041
Create Date: 2026-05-22 08:35:58.710492
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "d7dd938017a7"
down_revision: str | None = "9bca2a281041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("pipeline_item_owner_id_fkey"), "pipeline_item", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("pipeline_item_owner_id_fkey"),
        "pipeline_item",
        "accounts_member",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
