"""F1 icp: icp_definition table

Revision ID: f34304357c27
Revises: 467a515ea5a6
Create Date: 2026-05-22 08:18:36.213055
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f34304357c27"
down_revision: str | None = "467a515ea5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icp_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "countries",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "states",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "entity_kinds",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "signal_types",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("min_size", sa.Integer(), nullable=True),
        sa.Column("max_size", sa.Integer(), nullable=True),
        sa.Column(
            "signal_weights",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "keywords_required",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "keywords_excluded",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("deal_band_min_cents", sa.Integer(), nullable=True),
        sa.Column("deal_band_max_cents", sa.Integer(), nullable=True),
        sa.Column("threshold", sa.Integer(), server_default=sa.text("50"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["accounts_workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_icp_definition_countries",
        "icp_definition",
        ["countries"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_icp_definition_entity_kinds",
        "icp_definition",
        ["entity_kinds"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_icp_definition_signal_types",
        "icp_definition",
        ["signal_types"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_icp_definition_states",
        "icp_definition",
        ["states"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_icp_definition_workspace_id"), "icp_definition", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_icp_definition_one_active_per_workspace",
        "icp_definition",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_icp_definition_one_active_per_workspace",
        table_name="icp_definition",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_icp_definition_workspace_id"), table_name="icp_definition")
    op.drop_index("ix_icp_definition_states", table_name="icp_definition", postgresql_using="gin")
    op.drop_index(
        "ix_icp_definition_signal_types", table_name="icp_definition", postgresql_using="gin"
    )
    op.drop_index(
        "ix_icp_definition_entity_kinds", table_name="icp_definition", postgresql_using="gin"
    )
    op.drop_index(
        "ix_icp_definition_countries", table_name="icp_definition", postgresql_using="gin"
    )
    op.drop_table("icp_definition")
    # ### end Alembic commands ###
