"""entities: kind, geo, entity tables

Creates the global entity directory (C1, doc 07 §2): the ``entities_kind``
taxonomy, the ``entities_geo`` FIPS geography table, and the ``entities_entity``
org table with its hierarchical ``parent_id`` self-FK. Enables ``pg_trgm`` so the
``entities_name_trgm_idx`` GIN index can use ``gin_trgm_ops`` for name search
(doc 07 §2). Touches only ``entities_*`` objects (doc 06 §4 ownership).

Revision ID: f8de6b788783
Revises:
Create Date: 2026-05-22 05:39:09.986320
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f8de6b788783"
# Chained onto the current main head (the auth/ingestion/extraction merge
# revision) so Alembic history stays linear (single head) — see MIGRATION RULE.
down_revision: str | None = "aa34b8a78218"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pg_trgm backs the trigram GIN index on entities_entity.name (doc 07 §2).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities_geo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("geo_id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.String(length=2), server_default=sa.text("'US'"), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("state_fips", sa.String(length=2), nullable=True),
        sa.Column("county_fips", sa.String(length=5), nullable=True),
        sa.Column("place_fips", sa.String(length=7), nullable=True),
        sa.Column("parent_geo_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('state', 'county', 'place')", name="entities_geo_level_check"
        ),
        sa.ForeignKeyConstraint(["parent_geo_id"], ["entities_geo.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geo_id"),
    )
    op.create_index(
        "entities_geo_level_state_idx", "entities_geo", ["level", "state"], unique=False
    )
    op.create_index("entities_geo_state_idx", "entities_geo", ["state"], unique=False)
    op.create_table(
        "entities_kind",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug IN ('state', 'county', 'city', 'town', 'village', 'school_district', 'school', 'university', 'community_college', 'special_district', 'agency', 'authority', 'library_system', 'transit')",
            name="entities_kind_slug_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("entities_kind_category_idx", "entities_kind", ["category"], unique=False)
    op.create_table(
        "entities_entity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), server_default=sa.text("'US'"), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("kind_id", sa.UUID(), nullable=True),
        sa.Column("geo_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("nces_leaid", sa.String(length=16), nullable=True),
        sa.Column("ipeds_unitid", sa.String(length=16), nullable=True),
        sa.Column("census_gid", sa.String(length=32), nullable=True),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("enrollment", sa.Integer(), nullable=True),
        sa.Column("annual_budget_usd", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("primary_website", sa.Text(), nullable=True),
        sa.Column("procurement_portal_url", sa.Text(), nullable=True),
        sa.Column("board_meeting_cadence", sa.Text(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_urls",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'dissolved', 'merged')", name="entities_entity_status_check"
        ),
        sa.CheckConstraint(
            "type IN ('state', 'county', 'city', 'town', 'village', 'school_district', 'school', 'university', 'community_college', 'special_district', 'agency', 'authority', 'library_system', 'transit')",
            name="entities_entity_type_check",
        ),
        sa.ForeignKeyConstraint(["geo_id"], ["entities_geo.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["kind_id"], ["entities_kind.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["entities_entity.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("census_gid"),
        sa.UniqueConstraint("ipeds_unitid"),
        sa.UniqueConstraint("nces_leaid"),
    )
    op.create_index("entities_geo_fk_idx", "entities_entity", ["geo_id"], unique=False)
    op.create_index("entities_kind_fk_idx", "entities_entity", ["kind_id"], unique=False)
    op.create_index(
        "entities_name_trgm_idx",
        "entities_entity",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("entities_parent_idx", "entities_entity", ["parent_id"], unique=False)
    op.create_index("entities_state_type_idx", "entities_entity", ["state", "type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("entities_state_type_idx", table_name="entities_entity")
    op.drop_index("entities_parent_idx", table_name="entities_entity")
    op.drop_index(
        "entities_name_trgm_idx",
        table_name="entities_entity",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("entities_kind_fk_idx", table_name="entities_entity")
    op.drop_index("entities_geo_fk_idx", table_name="entities_entity")
    op.drop_table("entities_entity")
    op.drop_index("entities_kind_category_idx", table_name="entities_kind")
    op.drop_table("entities_kind")
    op.drop_index("entities_geo_state_idx", table_name="entities_geo")
    op.drop_index("entities_geo_level_state_idx", table_name="entities_geo")
    op.drop_table("entities_geo")
    # ### end Alembic commands ###
