"""recipes: quality_sample table for extraction quality sampling (QA-7)

Adds ``recipes_quality_sample`` — the review queue populated by the weekly
beat task ``recipes.sample_extraction_quality``. One row per sampled signal
per ISO-week window; captures the extracted field snapshot + per-field
accuracy judgements recorded by operators.

Revision ID: qa7_a1b2c3d4e5f6
Revises: d7c6c4b3e3d1
Create Date: 2026-05-22 10:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "qa7_a1b2c3d4e5f6"
# Chains onto the current main head (d7c6c4b3e3d1) so Alembic history stays
# linear (single head) — see MIGRATION RULE in CLAUDE.md.
down_revision: str | None = "d7c6c4b3e3d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes_quality_sample",
        sa.Column("id", sa.UUID(), nullable=False),
        # Loose ref to signals_signal.id (no FK — cross-module boundary, doc 06 §3).
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.String(length=255), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=False),
        sa.Column(
            "field_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        # ISO-week label for idempotency guard (e.g. "2026-W21").
        sa.Column("sample_window", sa.String(length=16), nullable=False),
        sa.Column(
            "sampled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Review fields — all nullable until reviewed.
        sa.Column(
            "field_judgements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("overall_accuracy", sa.Float(), nullable=True),
        sa.Column("reviewer", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recipes_quality_sample_signal_id",
        "recipes_quality_sample",
        ["signal_id"],
        unique=False,
    )
    op.create_index(
        "ix_recipes_quality_sample_recipe_id",
        "recipes_quality_sample",
        ["recipe_id"],
        unique=False,
    )
    op.create_index(
        "ix_recipes_quality_sample_sample_window",
        "recipes_quality_sample",
        ["sample_window"],
        unique=False,
    )
    op.create_index(
        "ix_recipes_quality_sample_recipe_window",
        "recipes_quality_sample",
        ["recipe_id", "sample_window"],
        unique=False,
    )
    op.create_index(
        "ix_recipes_quality_sample_window_sampled",
        "recipes_quality_sample",
        ["sample_window", "sampled_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_recipes_quality_sample_window_sampled",
        table_name="recipes_quality_sample",
    )
    op.drop_index(
        "ix_recipes_quality_sample_recipe_window",
        table_name="recipes_quality_sample",
    )
    op.drop_index(
        "ix_recipes_quality_sample_sample_window",
        table_name="recipes_quality_sample",
    )
    op.drop_index(
        "ix_recipes_quality_sample_recipe_id",
        table_name="recipes_quality_sample",
    )
    op.drop_index(
        "ix_recipes_quality_sample_signal_id",
        table_name="recipes_quality_sample",
    )
    op.drop_table("recipes_quality_sample")
    # ### end Alembic commands ###
